dist: trusty
language: cpp
addons:
  apt:
    packages:
    - libgsl0-dev
before_install:
  - pip2.7 install --user numpy scipy
  - pip2.7 install --user ete2
install:
  - g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`
script:
  - python2 evolve.py ssm_data.txt cnv_data.txt
