#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool
baseCommand: ['python','/evolve.py']

dct:creator:
  foaf:name: Quaid Morris 

dct:contributor:
  foaf:name: Jeff Wintersinger 

dct:contributor:
  foaf:name: Denis Yuen
  foaf:mbox: mailto:denis.yuen@oicr.on.ca


doc: |
  Run PhyloWGS to infer subclonal composition from SSMs and CNVs

requirements:
- class: DockerRequirement
  dockerPull: quay.io/dockstore/phylowgs:master 


inputs:
  
  - id: write_backups_every
    type: ["null", int]
    default: 100
    doc: Number of iterations to go between writing backups of program state
    inputBinding:
      prefix: --write-backups-every 

  - id: write_state_every
    type: ["null", int]
    default: 10
    doc: Number of iterations between writing program state to disk. Higher values reduce IO burden at the cost of losing progress made if program is interrupted.
    inputBinding:
      prefix: --write-state-every 

  - id: burnin_samples
    type: ["null", int]
    default: 1000
    doc: Number of burnin samples
    inputBinding:
      prefix: --burnin-samples 

  - id: mcmc_samples
    type: ["null", int]
    default: 2500
    doc: Number of MCMC samples
    inputBinding:
      prefix: --mcmc-samples 

  - id: mh_iterations
    type: ["null", int]
    default: 5000
    doc: Number of Metropolis-Hastings iterations
    inputBinding:
      prefix: --mh-iterations 

  - id: random_seed
    type: ["null", int]
    doc: Random seed for initializing MCMC sampler
    inputBinding:
      prefix: --random-seed 

  - id: params_file
    type: ["null", string]
    doc: JSON file listing run parameters, generated by the parser
    inputBinding:
      prefix: --params 

  - id: ssm_file
    type: File 
    doc: File listing SSMs (simple somatic mutations, i.e., single nucleotide variants. For proper format, see README.md.
    inputBinding:
      position: 1

  - id: cnv_file
    type: File 
    doc: File listing CNVs (copy number variations). For proper format, see README.md.
    inputBinding:
      position: 2


outputs:

  - id: clonal_frequencies
    type: File 
    doc: <Fill me in> 
    outputBinding: 
      glob: clonalFrequencies
    format: "http://edamontology.org/format_3752"

  - id: mcmc_samples_output
    type: File 
    doc: <Fill me in> 
    outputBinding: 
      glob: mcmc_samples.txt 
    format: "http://edamontology.org/format_3475"

  - id: random_seed_output
    type: File 
    doc: <Fill me in> 
    outputBinding: 
      glob: random_seed.txt 

  - id: top_k_trees
    type: File 
    doc: <Fill me in> 
    outputBinding: 
      glob: top_k_trees

  - id: trees
    type: File 
    doc: <Fill me in> 
    outputBinding: 
      glob: trees.zip
